version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mysql/server:2019-CU5-ubuntu-18.04
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong@Passw0rd
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: YourStrong@Passw0rd
